version: '3.8'

services:
  nlp:
    build: ./nlp
    ports:
      - "1234:1234"
    restart: always

  crawler:
    build: ./crawler
    depends_on:
      - nlp
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://nlp:1234
    depends_on:
      - nlp
    restart: always